language: python

python:
  - 3.6

before_install:
  - export TZ='Asia/Shanghai'

install:
  - pip install mkdocs
  - pip install pymdown-extensions
  - pip install mkdocs-material

script:
  - mkdocs build

branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  name: $GIT_NAME
  email: $GIT_EMAIL
  local_dir: site
  on:
    branch: master
